# **Exp 05: To perform the correlation operation of two discrete signals in Python**

## Package Required : Numpy

### Sample Program

In [1]:
import numpy as np
x=[1,2,3]
h=[2,3,4]
y=np.correlate(x,h,"full")
print(y)

[ 4 11 20 13  6]


# Programming Exercise 01

## Determine the correlation of the following signals

---


## 	x(n) = {1,2,3,4} and y(n) = {4,3,2,1}


In [2]:
import numpy as np
x=[1,2,3,4]
h=[4,3,2,1]
y=np.correlate(x,h,"full")
print(y)

[ 1  4 10 20 25 24 16]


# Programming Exercise 02




## Determine the autoconvolution of the following signal
## 	x(n) = {4,4,4,4} 

In [3]:
import numpy as np
x=[4,4,4,4]
y=np.correlate(x,x,"full")
print(y)

[16 32 48 64 48 32 16]
