# **Exp 04: To perform the convolution operation of two discrete signals in Python**

## Package Require : Numpy

### Sample Program

In [1]:
import numpy as np
x=[1,2,3]
h=[2,3,4]
y=np.correlate(x,h,"full")
print(y)

[ 4 11 20 13  6]


# Programming Exercise 01

## Determine the convolution of the following signals
## 	x(n) = {1,2,3,4} and h(n) = {4,3,2,1}


In [2]:
import numpy as np
x=[1,2,3,4]
h=[4,3,2,1]
y=np.convolve(x,h)
print(y)

[ 4 11 20 30 20 11  4]


# Programming Exercise 02


## Determine the convolution of the following signals
## 	x(n) = {4,4,4,4} and h(n) = {3,3,3}

In [3]:
import numpy as np
x=[4,4,4,4]
h=[3,3,3]
y=np.convolve(x,h)
print(y)

[12 24 36 36 24 12]
